### ISSUE TITLE
interactive version

### ISSUE THREAD

**Issue by nealhaddaway** [DrMattG/ES_Ecosystem#1]
Amazing, thanks Matt! My brain isn't in gear yet, but what's the best way of getting the interactive html version?

**Comment by DrMattG** [comment]
Can you get it through one of these links:

* Browse this gist on github:
   https://gist.github.com/bca6decd7feb9325a53cdda87ffbcce3
* View or share this gist on bl.ocks.org:
   http://bl.ocks.org/DrMattG/bca6decd7feb9325a53cdda87ffbcce3
* Embed in an iframe:
   <iframe width='820' height='820' frameBorder='0' webkitallowfullscreen='' mozallowfullscreen='' allowfullscreen='' sandbox='allow-forms allow-scripts allow-popups allow-same-origin allow-pointer-lock' src='https://cdn.rawgit.com/DrMattG/bca6decd7feb9325a53cdda87ffbcce3/raw/a55e6c50237ea746295e7732a482737365303db2/index.html'></iframe>

**Comment by nealhaddaway** [comment]
Perfect, thanks!
________________________________
